### ISSUE TITLE
Enable load of markdown file from asset

### ISSUE THREAD

**Issue by pasca-l** [pasca-l/log-search-app#3]
After writing the path to asset in `pubspec.yaml`, the asset should be accessible by `rootBundle.loadString`.
```yaml
flutter:
  assets:
    - assets/documents/test.md
```
```dart
file = rootBundle.loadString('assets/documents/test.md');
```

However, currently an error is raised `Error: Unable to load asset: "assets/documents/test.md". The asset does not exist or has empty data`.
